-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/access_control.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o = {}
    local key_file = luardb.get('service.webserver.https_key') or '/usr/local/cdcs//webserver/httpswebserver.key'
    local cert_file = luardb.get('service.webserver.https_cert') or '/usr/local/cdcs//webserver/httpswebserver.crt'
    o.isCertiValid = file_exists(key_file) and file_exists(cert_file)
    o.httpsServerEn = luardb.get('service.webserver.https_enabled')
    o.httpServerPort = luardb.get('service.webserver.http_port')
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
