-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/dhcp.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o = {}
    f = io.open('/var/run/data/dnsmasq.leases')
    local index=0
    if (f) then
      for line in f:lines() do
        local leaseArr = line:explode(' ')
        local lease = {}
        local expiry = tonumber(leaseArr[1])
        if not expiry then break end
        if expiry < 1585699200 then
          local uptime
          for line in io.lines('/proc/uptime') do
            local timeArr = line:explode(' ')
            uptime = math.floor(tonumber(timeArr[1]))
            break
          end
          local timeTbl = executeCommand('date +%s')
          timeOffset = tonumber(timeTbl[1]) - uptime
          expiry = expiry + timeOffset
        end
        local cmd = 'date -d @'..expiry
        local timeTbl = executeCommand(cmd)
        lease.lexpiry = timeTbl[1]
        lease.lmac = leaseArr[2]
        lease.lip = leaseArr[3]
        lease.lname = leaseArr[4]
        lease.__id=index
        index=index+1
        table.insert(o, lease)
      end
      f:close()
    end
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
