-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/dns_server.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.dns1=getRdb('service.dns.server.1')
    o.dns2=getRdb('service.dns.server.2')
    o.cacheSize=getRdb('service.dns.cache_size')
    o.localTtl=getRdb('service.dns.local_ttl')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.dns1 if #v > 0 then if isValid.IpAddress(v)==false then return false,'oops! '..'dns1' end end
    v=o.dns2 if #v > 0 then if isValid.IpAddress(v)==false then return false,'oops! '..'dns2' end end
    v=o.cacheSize if isValid.BoundedInteger(v,0,5000)==false then return false,'oops! '..'cacheSize' end
    v=o.localTtl if isValid.BoundedInteger(v,0,86400)==false then return false,'oops! '..'localTtl' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.dns1 setRdb('service.dns.server.1',v)
    v=o.dns2 setRdb('service.dns.server.2',v)
    v=o.cacheSize setRdb('service.dns.cache_size',v)
    v=o.localTtl setRdb('service.dns.local_ttl',v)
    until(true)
    luardb.set('service.dhcp.static.trigger','1')
    luardb.unlock()
  end
}
