-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/dhcp.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.enable=getRdb('service.dhcp.enable')
    
    local rdbs = getDefaultRouteLanRdbs()
    o.lanIp = luardb.get(rdbs.rdbAddrPrefix..'address')
    o.lanMask = luardb.get(rdbs.rdbAddrPrefix..'netmask')
    o.startRange = luardb.get(rdbs.rdbDhcp)
    o.leaseTime = luardb.get(rdbs.rdbLease)
    o.ipPassthroughActivated = isIpPassThroughActive()
  
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enable' end if toBool(v) == false then return true end
    v=o.startRange if isValid.IpAddress(v)==false then return false,'oops! '..'startRange' end
    v=o.endRange if isValid.IpAddress(v)==false then return false,'oops! '..'endRange' end
    v=o.leaseTime if isValid.BoundedInteger(v,120,99999)==false or (#v<=5)==false then return false,'oops! '..'leaseTime' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.enable setRdb('service.dhcp.enable',v) if toBool(v) == false then break end
    until(true)
    
    local rdbs = getDefaultRouteLanRdbs()
    luardb.set(rdbs.rdbDhcp, o.startRange)
    luardb.set(rdbs.rdbLease, o.leaseTime)
    luardb.set(rdbs.trigger,'1')
  
  end
}
