-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/NAT.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    =getRdbArray(authenticated,'service.firewall.dnat',0,49,true,{''})
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.ruleName if (#v<=32)==false or isValidName(v)==false then return false,'oops! '..'ruleName' end
    v=o.indexNo if isValid.BoundedInteger(v,1,6)==false then return false,'oops! '..'indexNo' end
    v=o.prot if isValid.Enum(v,{'TCP','UDP','TCP/UDP'})==false then return false,'oops! '..'prot' end
    v=o.oport if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'oport' end
    v=o.dip if isValid.IpAddress(v)==false then return false,'oops! '..'dip' end
    v=o.dport if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'dport' end
    v=o.enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local objs = o.objs
    for _, r in ipairs(objs) do
      r.rawdata = r.ruleName..','..r.enable..','..r.indexNo..','
      r.rawdata = r.rawdata..r.oport..','..r.dip..','..r.dport..','..r.prot
    end
    local termObj = {} termObj.__id=#o.objs  termObj.rawdata = '' o.objs[#o.objs+1]=termObj
    local rc = setRdbArray(authenticated,'service.firewall.dnat',{''},o)
    luardb.set('service.firewall.dnat.trigger','1')
    return rc
  end
}
