-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/upgrade.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.firmware=getFiles('/usrdata/cache/upgrade.star')
    o.defLanIpAddr, o.defHttpEn, o.defHttpsEn, o.defHttpsWebServerEn = getDefConfLanRdbs('factory', requestHandler.request.host)
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.resetConf if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'resetConf' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
    if o.resetConf == '1' then
      executeCommand('environment -w FACTORY_RESET NEEDED')
    end
  end
}
