-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_configuration.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.GpsEnable=getRdb('sensors.gps.0.enable')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.GpsEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'GpsEnable' end if toBool(v) == false then return true end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.GpsEnable setRdb('sensors.gps.0.enable',v) if toBool(v) == false then break end
    until(true)
    luardb.unlock()
  end
}
