-- auto generated by luaScriptGen.js.
local turbo=require('turbo')
function isValidCountryName(val)
 if val and #val >= 1 and #val <= 2 and val:match('[A-Z][A-Z]') then
  return true
 end
 return false
end
objHandler = {
  pageURL='/web_server_setting.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.keySize=getRdb('service.webserver.https_keysize')
    o.country=getRdb('service.webserver.https_country')
    o.state=getRdb('service.webserver.https_state')
    o.city=getRdb('service.webserver.https_city')
    o.org=getRdb('service.webserver.https_org')
    o.email=getRdb('service.webserver.https_email')
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.keySize if isValid.Enum(v,{'2048','4096'})==false then return false,'oops! '..'keySize' end
    v=o.country if (#v<=2)==false or (#v>=2)==false or isValidCountryName(v)==false then return false,'oops! '..'country' end
    v=o.state if (#v<=64)==false then return false,'oops! '..'state' end
    v=o.city if (#v<=64)==false then return false,'oops! '..'city' end
    v=o.org if (#v<=64)==false then return false,'oops! '..'org' end
    v=o.email if (#v<=64)==false then return false,'oops! '..'email' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.keySize v=turbo.escape.html_escape(v) setRdb('service.webserver.https_keysize',v)
    v=o.country v=turbo.escape.html_escape(v) setRdb('service.webserver.https_country',v,true)
    v=o.state v=turbo.escape.html_escape(v) setRdb('service.webserver.https_state',v,true)
    v=o.city v=turbo.escape.html_escape(v) setRdb('service.webserver.https_city',v,true)
    v=o.org v=turbo.escape.html_escape(v) setRdb('service.webserver.https_org',v,true)
    v=o.email v=turbo.escape.html_escape(v) setRdb('service.webserver.https_email',v,true)
    until(true)
  end
}
