-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_geofence.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.geofenceEnable=getRdb('sensors.gps.0.geofence.enable')
    o.coordUnitSel=getRdb('sensors.gps.0.geofence.display_decimaldegree')
    o.measSysSel=getRdb('sensors.gps.0.geofence.display_miles')
    o.currLati=getRdb('sensors.gps.0.common.latitude')
    o.currLatiDir=getRdb('sensors.gps.0.common.latitude_direction')
    o.currLong=getRdb('sensors.gps.0.common.longitude')
    o.currLongDir=getRdb('sensors.gps.0.common.longitude_direction')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.geofenceEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'geofenceEnable' end if toBool(v) == false then return true end
    v=o.coordUnitSel if isValid.Enum(v,{'0','1'})==false then return false,'oops! '..'coordUnitSel' end
    v=o.measSysSel if isValid.Enum(v,{'0','1'})==false then return false,'oops! '..'measSysSel' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.geofenceEnable setRdb('sensors.gps.0.geofence.enable',v) if toBool(v) == false then break end
    v=o.coordUnitSel setRdb('sensors.gps.0.geofence.display_decimaldegree',v)
    v=o.measSysSel setRdb('sensors.gps.0.geofence.display_miles',v)
    v=o.currLati setRdb('sensors.gps.0.common.latitude',v)
    v=o.currLatiDir setRdb('sensors.gps.0.common.latitude_direction',v)
    v=o.currLong setRdb('sensors.gps.0.common.longitude',v)
    v=o.currLongDir setRdb('sensors.gps.0.common.longitude_direction',v)
    until(true)
    luardb.unlock()
  end
}
