-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_geofence.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    
        local rawobj=getRdbArray(authenticated,'sensors.gps.0.geofence.circular',1,50,false,{'name', 'lati', 'long', 'radius', 'status'})
        for idx, obj in ipairs(rawobj) do
          if rawobj[idx]['name'] ~= '' then
            table.insert(o, rawobj[idx])
          end
        end
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.name if (#v<=32)==false or isValidName(v)==false then return false,'oops! '..'name' end
    v=o.lati_dd if isValid.BoundedSignedFloat(v,-90,90)==false then return false,'oops! '..'lati_dd' end
    v=o.long_dd if isValid.BoundedSignedFloat(v,-180,180)==false then return false,'oops! '..'long_dd' end
    v=o.lati_dms if isValid.DmsField('lati', v)==false then return false,'oops! '..'lati_dms' end
    v=o.long_dms if isValid.DmsField('long', v)==false then return false,'oops! '..'long_dms' end
    v=o.radius_km if isValid.BoundedFloat(v,0,99999)==false then return false,'oops! '..'radius_km' end
    v=o.radius_mi if isValid.BoundedFloat(v,0,99999)==false then return false,'oops! '..'radius_mi' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
    
        local indices = collect_indices(o.objs)
        luardb.set('sensors.gps.0.geofence.circular._index', indices, 'p')
        local rc = setRdbArray(authenticated,'sensors.gps.0.geofence.circular',{'name', 'lati', 'long', 'radius', 'status'},o)
        luardb.set('sensors.gps.0.geofence.daemon.trigger', '1')
        return rc
    
  end
}
