-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_configuration.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.latitude=getRdb('sensors.gps.0.common.latitude')
    o.longitude=getRdb('sensors.gps.0.common.longitude')
    o.gps_source=getRdb('sensors.gps.0.source')
    o.gps_standalone_valid=getRdb('sensors.gps.0.standalone.valid')
    o.gps_assisted_valid=getRdb('sensors.gps.0.assisted.valid')
    o.gps_common_date=getRdb('sensors.gps.0.common.date')
    o.gps_common_time=getRdb('sensors.gps.0.common.time')
    o.latitude_direction=getRdb('sensors.gps.0.common.latitude_direction')
    o.latitude=getRdb('sensors.gps.0.common.latitude')
    o.longitude_direction=getRdb('sensors.gps.0.common.longitude_direction')
    o.longitude=getRdb('sensors.gps.0.common.longitude')
    o.altitude=getRdb('sensors.gps.0.standalone.altitude')
    o.hspeed=getRdb('sensors.gps.0.standalone.horizontal_speed')
    o.vspeed=getRdb('sensors.gps.0.standalone.vertical_speed')
    o.height_of_geoid=getRdb('sensors.gps.0.common.height_of_geoid')
    o.pdop=getRdb('sensors.gps.0.standalone.pdop')
    o.hdop=getRdb('sensors.gps.0.standalone.hdop')
    o.vdop=getRdb('sensors.gps.0.standalone.vdop')
    o.number_of_satellites=getRdb('sensors.gps.0.standalone.number_of_satellites')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.latitude setRdb('sensors.gps.0.common.latitude',v)
    v=o.longitude setRdb('sensors.gps.0.common.longitude',v)
    v=o.gps_source setRdb('sensors.gps.0.source',v)
    v=o.gps_standalone_valid setRdb('sensors.gps.0.standalone.valid',v)
    v=o.gps_assisted_valid setRdb('sensors.gps.0.assisted.valid',v)
    v=o.gps_common_date setRdb('sensors.gps.0.common.date',v)
    v=o.gps_common_time setRdb('sensors.gps.0.common.time',v)
    v=o.latitude_direction setRdb('sensors.gps.0.common.latitude_direction',v)
    v=o.latitude setRdb('sensors.gps.0.common.latitude',v)
    v=o.longitude_direction setRdb('sensors.gps.0.common.longitude_direction',v)
    v=o.longitude setRdb('sensors.gps.0.common.longitude',v)
    v=o.altitude setRdb('sensors.gps.0.standalone.altitude',v)
    v=o.hspeed setRdb('sensors.gps.0.standalone.horizontal_speed',v)
    v=o.vspeed setRdb('sensors.gps.0.standalone.vertical_speed',v)
    v=o.height_of_geoid setRdb('sensors.gps.0.common.height_of_geoid',v)
    v=o.pdop setRdb('sensors.gps.0.standalone.pdop',v)
    v=o.hdop setRdb('sensors.gps.0.standalone.hdop',v)
    v=o.vdop setRdb('sensors.gps.0.standalone.vdop',v)
    v=o.number_of_satellites setRdb('sensors.gps.0.standalone.number_of_satellites',v)
    until(true)
    luardb.unlock()
  end
}
