-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/FactoryReset.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.lastBootDuration=getRdb('system.startup_duration')
    
      o.defLanIpAddr, o.defHttpEn, o.defHttpsEn, o.defHttpsWebServerEn = getDefConfLanRdbs('installer', requestHandler.request.host)
      o.rebootTimeSecs = config.REBOOT_TIME_SECS
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
    
      luardb.set('service.factoryreset.reason', 'webui')
      luardb.set('service.system.factory.level', 'installer')
      luardb.set('service.system.factory.clear_https_cert', o.clearHttpsCert)
      luardb.set('service.system.factory', '1')
    
  end
}
