-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/field_test.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    
        local sys_so = luardb.get("wwan.0.system_network_status.current_system_so")
        local attached = luardb.get("wwan.0.system_network_status.attached")
        if attached == "1" and not sys_so:find("5G SA") then
            local obj = {}
            if not sys_so:find("LTE CA") then
                obj["pci"] = luardb.get("wwan.0.system_network_status.PCID") or ""
                obj["freq"] = luardb.get("wwan.0.system_network_status.channel") or ""
                local band = luardb.get("wwan.0.system_network_status.current_band") or ""
                obj["band"] = string.match(band, "LTE Band (%d+)") or ""
                local bandwidth = luardb.get("wwan.0.system_network_status.current_rf_bandwidth") or ""
                obj["bandwidth"] = string.match(bandwidth, "LTE ([%.%d]+MHz)") or ""
            else
                obj["pci"] = luardb.get("wwan.0.system_network_status.lte_ca_pcell.pci") or ""
                obj["freq"] = luardb.get("wwan.0.system_network_status.lte_ca_pcell.freq") or ""
                obj["band"] = luardb.get("wwan.0.system_network_status.lte_ca_pcell.band") or ""
                obj["bandwidth"] = luardb.get("wwan.0.system_network_status.lte_ca_pcell.bandwidth") or ""
            end
            obj.__id = 1
            if obj["pci"] ~= "" then o[1]=obj end
        end
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
