-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/lwm2m.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.Lwm2mEnable=getRdb('service.lwm2m.enable')
    o.endpoint=getRdb('service.lwm2m.endpoint')
    o.model=getRdb('system.product.model')
    o.sn=getRdb('system.product.sn')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.Lwm2mEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'Lwm2mEnable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.Lwm2mEnable setRdb('service.lwm2m.enable',v)
    v=o.endpoint setRdb('service.lwm2m.endpoint',v)
    v=o.model setRdb('system.product.model',v)
    v=o.sn setRdb('system.product.sn',v)
    until(true)
    luardb.unlock()
  end
}
