-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/logsettings.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.capturelevel=getRdb('service.syslog.option.capturelevel')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.capturelevel if isValid.Enum(v,{'8','7','6','5','4'})==false then return false,'oops! '..'capturelevel' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.capturelevel setRdb('service.syslog.option.capturelevel',v)
    until(true)
    luardb.unlock()
  end
}
