-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/profile_list.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    
    o=getRdbArray(authenticated,'link.profile',1,6,false,{'name','apn','ip_handover.enable', 'vlan_index', 'defaultroute'},false)
    combineRdbArray(o, getRdbArray(authenticated,'link.policy',1,6,false,{'enable'},false))
    for _, obj in ipairs(o) do
      obj['vlans'] = getVlanList(true)
      if obj['defaultroute'] == '1' then
        obj['vlans'][''] = obj['vlans']['-1']
      else
        obj['vlans'][''] = 'None'
      end
      obj['vlans']['-1'] = nil
    end
    if isIpPassThroughActive() == true then luardb.set('service.dhcp.enable', '1') end
  
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enable' end
    v=o.ho_enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'ho_enable' end
    v=o.defaultroute if isValid.Bool(v)==false then return false,'oops! '..'defaultroute' end
    
    for _, obj in ipairs(o) do
      if not isValid.Key(obj['vlan_index'], getVlanList(true)) and obj['vlan_index'] ~= '' then
        return false, 'oops! ' .. 'vlan_index'
      end
    end
  
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    until(true)
    for _, obj in ipairs(o.objs) do
      if obj.changed == '1' then
        rdbName = 'link.profile.' .. obj.__id .. '.'
        setRdb(rdbName .. 'ip_handover.enable', obj['ho_enable'])
        setRdb(rdbName .. 'vlan_index', obj['vlan_index'])
        setRdb(rdbName .. 'defaultroute', obj['defaultroute'])
        local rdbName = 'link.policy.' .. obj.__id .. '.'
        setRdb(rdbName .. 'enable', obj['enable'])
        setRdb(rdbName .. 'trigger_connect', obj['enable'])
      end
    end
    luardb.unlock()
  end
}
