-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/access_control.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.localHttpEnable=getRdb('admin.local.enable_http')
    o.localHttpsEnable=getRdb('admin.local.enable_https')
    o.localSshEnable=getRdb('admin.local.ssh_enable')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.localHttpEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'localHttpEnable' end
    v=o.localHttpsEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'localHttpsEnable' end
    v=o.localSshEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'localSshEnable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.localHttpEnable setRdb('admin.local.enable_http',v)
    v=o.localHttpsEnable setRdb('admin.local.enable_https',v)
    v=o.localSshEnable setRdb('admin.local.ssh_enable',v)
    until(true)
    luardb.unlock()
  end
}
