-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/field_test.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    
        local attached = luardb.get("wwan.0.system_network_status.attached")
        local sys_so = luardb.get("wwan.0.system_network_status.current_system_so")
        if attached == "1" and not sys_so:find("5G SA") then
            o = getRdbArray(authenticated,'wwan.0.system_network_status.lte_ca_scell.list',1,8,true,{'band','bandwidth','freq','pci','scell_idx','scell_state','ul_configured'})
        end
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
