-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/index.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.factoryDefault=getRdb('service.webui.need_generate_default_password')
    o.browserTime=getRdb('system.browser.time')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.factoryDefault setRdb('service.webui.need_generate_default_password',v)
    v=o.browserTime setRdb('system.browser.time',v)
    until(true)
    luardb.unlock()
  end
}
