-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/lan.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.lanHost=encode(getRdb('link.profile.0.hostname'))
    
    local rdbs = getDefaultRouteLanRdbs()
    o.lanIp = luardb.get(rdbs.rdbAddrPrefix..'address')
    o.lanMask = luardb.get(rdbs.rdbAddrPrefix..'netmask')
    o.dhcpRange = luardb.get(rdbs.rdbDhcp)
  
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.lanIp if isValid.IpAddress(v)==false then return false,'oops! '..'lanIp' end
    v=o.lanMask if isValid.IpMask(v)==false then return false,'oops! '..'lanMask' end
    v=o.lanHost v = decode(v) if isValid.Hostname(v)==false then return false,'oops! '..'lanHost' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.lanHost v=decode(v) setRdb('link.profile.0.hostname',v)
    until(true)
    
    local rdbs = getDefaultRouteLanRdbs()
    luardb.set(rdbs.rdbAddrPrefix..'address', o.lanIp)
    luardb.set(rdbs.rdbAddrPrefix..'netmask', o.lanMask)
    luardb.set(rdbs.rdbDhcp, o.dhcpRange)
    luardb.set(rdbs.trigger,'1')
  
  end
}
