-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/logfile.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.captureLevel=getRdb('service.syslog.option.capturelevel')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.captureLevel setRdb('service.syslog.option.capturelevel',v)
    until(true)
    luardb.unlock()
  end
}
