-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_odometer.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.resetTrig=getRdb('sensors.gps.0.odometer_reset')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.resetTrig setRdb('sensors.gps.0.odometer_reset',v)
    until(true)
    luardb.unlock()
  end
}
