-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/operator_setting.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.selMode=getRdb('wwan.0.PLMN_selectionMode')
    o.networkName=getRdb('wwan.0.system_network_status.network')
    o.networkType=getRdb('wwan.0.system_network_status.service_type')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.selMode setRdb('wwan.0.PLMN_selectionMode',v)
    v=o.networkName setRdb('wwan.0.system_network_status.network',v)
    v=o.networkType setRdb('wwan.0.system_network_status.service_type',v)
    until(true)
    luardb.unlock()
  end
}
