-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_odometer.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.enable=getRdb('sensors.gps.0.odometer_enable')
    o.threshold=getRdb('sensors.gps.0.odometer_threshold')
    o.measSysSel=getRdb('sensors.gps.0.odometer_miles')
    o.gpsEnabled=getRdb('sensors.gps.0.enable')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enable' end
    v=o.threshold if isValid.BoundedInteger(v,1,100)==false then return false,'oops! '..'threshold' end
    v=o.measSysSel if isValid.Enum(v,{'0','1'})==false then return false,'oops! '..'measSysSel' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.enable setRdb('sensors.gps.0.odometer_enable',v)
    v=o.threshold setRdb('sensors.gps.0.odometer_threshold',v)
    v=o.measSysSel setRdb('sensors.gps.0.odometer_miles',v)
    until(true)
    luardb.unlock()
  end
}
