-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/operator_setting.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    
      local plmnList = luardb.get('wwan.0.PLMN_list') or ''
      local plmnTbl = plmnList:explode('&')
      for _, plmn in ipairs(plmnTbl) do
        local netInfo = plmn:explode(',')
        local oper = {}
        oper.lname = netInfo[1]
        oper.lmcc = netInfo[2]
        oper.lmnc = netInfo[3]
        oper.lstatus = netInfo[4]
        oper.ltype = netInfo[5]
        if oper.lname ~= '' then
          table.insert(o, oper)
        end
      end
  
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.operSel if isValid.Bool(v)==false then return false,'oops! '..'operSel' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
