-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/lwm2m.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.overrideEnable=getRdb('service.lwm2m.override.enable')
    o.overrideOnce=getRdb('service.lwm2m.override.once')
    o.serverUri=getRdb('service.lwm2m.override.server-uri')
    o.regLifetime=getRdb('service.lwm2m.override.lifetime')
    o.bootstrap=getRdb('service.lwm2m.override.bootstrap')
    o.queueMode=getRdb('service.lwm2m.override.queue')
    o.secMode=getRdb('service.lwm2m.override.sec-mode')
    o.clientId=getRdb('service.lwm2m.override.psk-id')
    o.pskCoding=getRdb('service.lwm2m.override.psk-coding')
    o.pskKey=getRdb('service.lwm2m.override.psk-key')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.overrideEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'overrideEnable' end if toBool(v) == false then return true end
    v=o.overrideOnce if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'overrideOnce' end
    v=o.regLifetime if isValid.BoundedInteger(v,60,86400)==false then return false,'oops! '..'regLifetime' end
    v=o.bootstrap if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'bootstrap' end
    v=o.queueMode if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'queueMode' end
    v=o.secMode if isValid.Enum(v,{'nosec','psk'})==false then return false,'oops! '..'secMode' end
    v=o.pskCoding if isValid.Enum(v,{'hex','text'})==false then return false,'oops! '..'pskCoding' end
    if o.secMode == 'psk' then v=o.pskKey if (#v>=8)==false or (#v<=128)==false then return false,'oops! '..'pskKey' end end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.overrideEnable setRdb('service.lwm2m.override.enable',v) if toBool(v) == false then break end
    v=o.overrideOnce setRdb('service.lwm2m.override.once',v)
    v=o.serverUri setRdb('service.lwm2m.override.server-uri',v)
    v=o.regLifetime setRdb('service.lwm2m.override.lifetime',v)
    v=o.bootstrap setRdb('service.lwm2m.override.bootstrap',v)
    v=o.queueMode setRdb('service.lwm2m.override.queue',v)
    v=o.secMode setRdb('service.lwm2m.override.sec-mode',v)
    v=o.clientId setRdb('service.lwm2m.override.psk-id',v)
    v=o.pskCoding setRdb('service.lwm2m.override.psk-coding',v)
    if o.secMode == 'psk' then v=o.pskKey setRdb('service.lwm2m.override.psk-key',v) end
    until(true)
    luardb.unlock()
  end
}
