-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_odometer.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.odometerStartTime=getRdb('sensors.gps.0.odometer.starttime')
    o.odometer=getRdb('sensors.gps.0.odometer')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    until(true)
    luardb.unlock()
  end
}
