-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/ping_diag.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.diagState=getRdb('tr069.diagnostics.ipping.state')
    o.successCount=getRdb('tr069.diagnostics.ipping.success_count')
    o.failureCount=getRdb('tr069.diagnostics.ipping.failure_count')
    o.minRespTime=getRdb('tr069.diagnostics.ipping.min_rsp_time')
    o.maxRespTime=getRdb('tr069.diagnostics.ipping.max_rsp_time')
    o.avgRespTime=getRdb('tr069.diagnostics.ipping.avg_rsp_time')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.diagState setRdb('tr069.diagnostics.ipping.state',v)
    v=o.successCount setRdb('tr069.diagnostics.ipping.success_count',v)
    v=o.failureCount setRdb('tr069.diagnostics.ipping.failure_count',v)
    v=o.minRespTime setRdb('tr069.diagnostics.ipping.min_rsp_time',v)
    v=o.maxRespTime setRdb('tr069.diagnostics.ipping.max_rsp_time',v)
    v=o.avgRespTime setRdb('tr069.diagnostics.ipping.avg_rsp_time',v)
    until(true)
    luardb.unlock()
  end
}
