-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/profile_settings.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.profEnable=getRdb(string.format('link.policy.%d.enable', tonumber(objHandler.queryParams.id) or 1))
    o.profName=getRdb(string.format('link.profile.%d.name', tonumber(objHandler.queryParams.id) or 1))
    o.profApn=getRdb(string.format('link.profile.%d.apn', tonumber(objHandler.queryParams.id) or 1))
    o.profUser=getRdb(string.format('link.profile.%d.user', tonumber(objHandler.queryParams.id) or 1))
    o.profPasswd=encode(getRdb(string.format('link.profile.%d.pass', tonumber(objHandler.queryParams.id) or 1)))
    o.profAuthType=getRdb(string.format('link.profile.%d.auth_type', tonumber(objHandler.queryParams.id) or 1))
    o.profPdpType=getRdb(string.format('link.profile.%d.pdp_type', tonumber(objHandler.queryParams.id) or 1))
    o.mtuSize=getRdb(string.format('link.profile.%d.mtu', tonumber(objHandler.queryParams.id) or 1))
    o.profIpHandoverEnable=getRdb(string.format('link.profile.%d.ip_handover.enable', tonumber(objHandler.queryParams.id) or 1))
    o.profAdminAccessEnable=getRdb(string.format('link.profile.%d.admin_access_allowed', tonumber(objHandler.queryParams.id) or 1))
    o.profModemIdx=getRdb(string.format('link.profile.%d.module_profile_idx', tonumber(objHandler.queryParams.id) or 1))
    o.defaultroute=getRdb(string.format('link.profile.%d.defaultroute', tonumber(objHandler.queryParams.id) or 1))
    if isIpPassThroughActive() == true then luardb.set('service.dhcp.enable', '1') end
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.profEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'profEnable' end if toBool(v) == false then return true end
    v=o.profUser if #v > 0 then if isValid.Username(v)==false then return false,'oops! '..'profUser' end end
    v=o.profAuthType if isValid.Enum(v,{'chap','pap','none'})==false then return false,'oops! '..'profAuthType' end
    v=o.profPdpType if isValid.Enum(v,{'ipv4','ipv6','ipv4v6'})==false then return false,'oops! '..'profPdpType' end
    v=o.mtuSize if #v > 0 then if isValid.BoundedInteger(v,1,1500)==false then return false,'oops! '..'mtuSize' end end
    v=o.profIpHandoverEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'profIpHandoverEnable' end
    v=o.profAdminAccessEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'profAdminAccessEnable' end
    v=o.profModemIdx if isValid.Enum(v,{'1','2','3','4','5','6'})==false then return false,'oops! '..'profModemIdx' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.profEnable setRdb(string.format('link.policy.%d.enable', tonumber(objHandler.queryParams.id) or 1),v) if toBool(v) == false then break end
    v=o.profName setRdb(string.format('link.profile.%d.name', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profApn setRdb(string.format('link.profile.%d.apn', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profUser setRdb(string.format('link.profile.%d.user', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profPasswd v=decode(v) setRdb(string.format('link.profile.%d.pass', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profAuthType setRdb(string.format('link.profile.%d.auth_type', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profPdpType setRdb(string.format('link.profile.%d.pdp_type', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.mtuSize setRdb(string.format('link.profile.%d.mtu', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profIpHandoverEnable setRdb(string.format('link.profile.%d.ip_handover.enable', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profAdminAccessEnable setRdb(string.format('link.profile.%d.admin_access_allowed', tonumber(objHandler.queryParams.id) or 1),v)
    v=o.profModemIdx setRdb(string.format('link.profile.%d.module_profile_idx', tonumber(objHandler.queryParams.id) or 1),v)
    until(true)
    local index = tonumber(objHandler.queryParams.id) or 1
    luardb.set(string.format('link.profile.%d.writeflag', index), '1')
    luardb.set(string.format('link.policy.%d.trigger_connect', index), o.profEnable)
    luardb.unlock()
  end
}
