-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/ping_diag.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.pingHost=getRdb('tr069.diagnostics.ipping.host')
    o.pingRepeats=getRdb('tr069.diagnostics.ipping.reps')
    o.pingTimeout=getRdb('tr069.diagnostics.ipping.timeout')
    o.pingBlockSize=getRdb('tr069.diagnostics.ipping.blksz')
    o.pingDscp=getRdb('tr069.diagnostics.ipping.dscp')
    o.pingInterface=getRdb('tr069.diagnostics.ipping.interface_iface')
    o.pingProtocol=getRdb('tr069.diagnostics.ipping.proto')
    o.pingTriggerSrc=getRdb('tr069.diagnostics.ipping.trigger_src')
    o.pingState=getRdb('tr069.diagnostics.ipping.state')
    o.ifaces = getNetIfaces(true)
    local pidfile = '/var/run/tr143_ping.pid'
    local program = '/usr/lib/tr-069/scripts/tr143_diagd.lua'
    if not isDaemonRunning(pidfile) then startDaemon(program, pidfile, '-p') end
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.pingHost if (isValid.Hostname(v) or isValid.IpAddress(v) or isValid.Ipv6Address(v))==false then return false,'oops! '..'pingHost' end
    v=o.pingRepeats if isValid.BoundedInteger(v,1,4294967295)==false then return false,'oops! '..'pingRepeats' end
    v=o.pingTimeout if isValid.BoundedInteger(v,1,4294967295)==false then return false,'oops! '..'pingTimeout' end
    v=o.pingBlockSize if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'pingBlockSize' end
    v=o.pingDscp if isValid.BoundedInteger(v,0,63)==false then return false,'oops! '..'pingDscp' end
    v=o.pingProtocol if isValid.Enum(v,{'Any','IPv4','IPv6'})==false then return false,'oops! '..'pingProtocol' end
    v=o.pingInterface if not isValid.Enum(v, getNetIfaces(true)) and v ~= '' then return false,'oops! '..'pingInterface' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.pingHost setRdb('tr069.diagnostics.ipping.host',v)
    v=o.pingRepeats setRdb('tr069.diagnostics.ipping.reps',v)
    v=o.pingTimeout setRdb('tr069.diagnostics.ipping.timeout',v)
    v=o.pingBlockSize setRdb('tr069.diagnostics.ipping.blksz',v)
    v=o.pingDscp setRdb('tr069.diagnostics.ipping.dscp',v)
    v=o.pingInterface setRdb('tr069.diagnostics.ipping.interface_iface',v)
    v=o.pingProtocol setRdb('tr069.diagnostics.ipping.proto',v)
    v=o.pingTriggerSrc setRdb('tr069.diagnostics.ipping.trigger_src',v,true)
    v=o.pingState setRdb('tr069.diagnostics.ipping.state',v,true)
    until(true)
    luardb.unlock()
  end
}
