-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/logsettings.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.remoteEn=getRdb('service.syslog.option.logtoremote')
    o.remote=getRdb('service.syslog.option.remote')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.remote if #v > 0 then if isValid.HostnameWPort(v)==false then return false,'oops! '..'remote' end end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.remoteEn setRdb('service.syslog.option.logtoremote',v)
    v=o.remote setRdb('service.syslog.option.remote',v)
    until(true)
    setRdb('service.syslog.option.trigger', '1')
    luardb.unlock()
  end
}
