-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/runtime_config.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.rdbConfigIds=getRdb('runtime.config.rdb_ids')
    o.certConfigIds=getRdb('runtime.config.cert_ids')
    o.mbnConfigIds=getRdb('runtime.config.mbn_ids')
    o.efsConfigIds=getRdb('runtime.config.efs_ids')
    o.rdbConfigLevels=getRdb('runtime.config.rdb_levels')
    o.certConfigLevels=getRdb('runtime.config.cert_levels')
    o.mbnConfigLevels=getRdb('runtime.config.mbn_levels')
    o.efsConfigLevels=getRdb('runtime.config.efs_levels')
    o.rdbConfigVersions=getRdb('runtime.config.rdb_versions')
    o.certConfigVersions=getRdb('runtime.config.cert_versions')
    o.mbnConfigVersions=getRdb('runtime.config.mbn_versions')
    o.efsConfigVersions=getRdb('runtime.config.efs_versions')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.rdbConfigIds setRdb('runtime.config.rdb_ids',v)
    v=o.certConfigIds setRdb('runtime.config.cert_ids',v)
    v=o.mbnConfigIds setRdb('runtime.config.mbn_ids',v)
    v=o.efsConfigIds setRdb('runtime.config.efs_ids',v)
    v=o.rdbConfigLevels setRdb('runtime.config.rdb_levels',v)
    v=o.certConfigLevels setRdb('runtime.config.cert_levels',v)
    v=o.mbnConfigLevels setRdb('runtime.config.mbn_levels',v)
    v=o.efsConfigLevels setRdb('runtime.config.efs_levels',v)
    v=o.rdbConfigVersions setRdb('runtime.config.rdb_versions',v)
    v=o.certConfigVersions setRdb('runtime.config.cert_versions',v)
    v=o.mbnConfigVersions setRdb('runtime.config.mbn_versions',v)
    v=o.efsConfigVersions setRdb('runtime.config.efs_versions',v)
    until(true)
    luardb.unlock()
  end
}
