-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/settings_backup.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.configFileUploader=getFiles('/usrdata/cache/settingsBackup.zip')
    o.lastBootDuration=getRdb('system.startup_duration')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    until(true)
    
      luardb.set("service.system.reset_reason", "Webui Request")
      luardb.set("service.system.reset", "1")
    
    luardb.unlock()
  end
}
