-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/access_control.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.remoteHttpEnable=getRdb('admin.remote.webenable')
    o.httpPort=getRdb('admin.remote.port')
    o.remoteHttpsEnable=getRdb('admin.remote_https.enable')
    o.httpsPort=getRdb('admin.remote_https.port')
    o.httpsIpAllowList=getRdb('admin.remote_https.ip_whitelist')
    o.remoteSshEnable=getRdb('admin.remote.sshd_enable')
    o.sshPort=getRdb('admin.remote.sshd_port')
    o.remotePingEnable=getRdb('admin.remote.pingenable')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.remoteHttpEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'remoteHttpEnable' end
    v=o.httpPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'httpPort' end
    v=o.remoteHttpsEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'remoteHttpsEnable' end
    v=o.httpsPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'httpsPort' end
    v=o.remoteSshEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'remoteSshEnable' end
    v=o.sshPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'sshPort' end
    v=o.remotePingEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'remotePingEnable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.remoteHttpEnable setRdb('admin.remote.webenable',v)
    v=o.httpPort setRdb('admin.remote.port',v)
    v=o.remoteHttpsEnable setRdb('admin.remote_https.enable',v)
    v=o.httpsPort setRdb('admin.remote_https.port',v)
    v=o.httpsIpAllowList setRdb('admin.remote_https.ip_whitelist',v)
    v=o.remoteSshEnable setRdb('admin.remote.sshd_enable',v)
    v=o.sshPort setRdb('admin.remote.sshd_port',v)
    v=o.remotePingEnable setRdb('admin.remote.pingenable',v)
    until(true)
    luardb.unlock()
  end
}
