-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/roaming.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.voiceRoam=getRdb('roaming.voice.en')
    o.dataRoam=getRdb('roaming.data.en')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.roamingEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'roamingEnable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.voiceRoam setRdb('roaming.voice.en',v)
    v=o.dataRoam setRdb('roaming.data.en',v)
    until(true)
    luardb.unlock()
  end
}
