-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.MCC=getRdb('wwan.0.system_network_status.MCC')
    o.MNC=getRdb('wwan.0.system_network_status.MNC')
    o.simICCID=getRdb('wwan.0.system_network_status.simICCID')
    o.IMSI=getRdb('wwan.0.imsi.msin')
    o.psAttached=getRdb('wwan.0.system_network_status.attached')
    o.ECGI=getRdb('wwan.0.system_network_status.ECGI')
    o.enodeB=getRdb('wwan.0.system_network_status.eNB_ID')
    o.cellId=getRdb('wwan.0.system_network_status.CellID')
    o.pci=getRdb('wwan.0.system_network_status.PCID')
    o.earfcn=getRdb('wwan.0.system_network_status.channel')
    o.rsrp=getRdb('wwan.0.signal.0.rsrp')
    o.rsrq=getRdb('wwan.0.signal.rsrq')
    o.snr=getRdb('wwan.0.signal.snr')
    o.cqi=getRdb('wwan.0.servcell_info.avg_wide_band_cqi')
    o.nr5g_ncgi=getRdb('wwan.0.radio_stack.nr5g.cgi')
    o.nr5g_gnodeB=getRdb('wwan.0.radio_stack.nr5g.gNB_ID')
    o.nr5g_cellId=getRdb('wwan.0.radio_stack.nr5g.CellID')
    o.nr5g_arfcn=getRdb('wwan.0.radio_stack.nr5g.arfcn')
    o.nr5g_ssb_arfcn=getRdb('wwan.0.radio_stack.nr5g.ssb_arfcn')
    o.nr5g_pci=getRdb('wwan.0.radio_stack.nr5g.pci')
    o.nr5g_scs=getRdb('wwan.0.radio_stack.nr5g.scs')
    o.nr5g_rsrp=getRdb('wwan.0.radio_stack.nr5g.rsrp')
    o.nr5g_rsrq=getRdb('wwan.0.radio_stack.nr5g.rsrq')
    o.nr5g_snr=getRdb('wwan.0.radio_stack.nr5g.snr')
    o.nr5g_cqi=getRdb('wwan.0.radio_stack.nr5g.cqi')
    o.nr5g_ssbIndex=getRdb('wwan.0.radio_stack.nr5g.ssb_index')
    o.sys_so=getRdb('wwan.0.system_network_status.current_system_so')
    o.scellBand=getRdb('wwan.0.system_network_status.lte_ca_scell.list.1.band')
    o.scellPci=getRdb('wwan.0.system_network_status.lte_ca_scell.list.1.pci')
    o.scellEarfcn=getRdb('wwan.0.system_network_status.lte_ca_scell.list.1.freq')
    o.scellState=getRdb('wwan.0.system_network_status.lte_ca_scell.list.1.scell_state')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.MCC setRdb('wwan.0.system_network_status.MCC',v)
    v=o.MNC setRdb('wwan.0.system_network_status.MNC',v)
    v=o.simICCID setRdb('wwan.0.system_network_status.simICCID',v)
    v=o.IMSI setRdb('wwan.0.imsi.msin',v)
    v=o.psAttached setRdb('wwan.0.system_network_status.attached',v)
    v=o.ECGI setRdb('wwan.0.system_network_status.ECGI',v)
    v=o.enodeB setRdb('wwan.0.system_network_status.eNB_ID',v)
    v=o.cellId setRdb('wwan.0.system_network_status.CellID',v)
    v=o.pci setRdb('wwan.0.system_network_status.PCID',v)
    v=o.earfcn setRdb('wwan.0.system_network_status.channel',v)
    v=o.rsrp setRdb('wwan.0.signal.0.rsrp',v)
    v=o.rsrq setRdb('wwan.0.signal.rsrq',v)
    v=o.snr setRdb('wwan.0.signal.snr',v)
    v=o.cqi setRdb('wwan.0.servcell_info.avg_wide_band_cqi',v)
    v=o.nr5g_ncgi setRdb('wwan.0.radio_stack.nr5g.cgi',v)
    v=o.nr5g_gnodeB setRdb('wwan.0.radio_stack.nr5g.gNB_ID',v)
    v=o.nr5g_cellId setRdb('wwan.0.radio_stack.nr5g.CellID',v)
    v=o.nr5g_arfcn setRdb('wwan.0.radio_stack.nr5g.arfcn',v)
    v=o.nr5g_ssb_arfcn setRdb('wwan.0.radio_stack.nr5g.ssb_arfcn',v)
    v=o.nr5g_pci setRdb('wwan.0.radio_stack.nr5g.pci',v)
    v=o.nr5g_scs setRdb('wwan.0.radio_stack.nr5g.scs',v)
    v=o.nr5g_rsrp setRdb('wwan.0.radio_stack.nr5g.rsrp',v)
    v=o.nr5g_rsrq setRdb('wwan.0.radio_stack.nr5g.rsrq',v)
    v=o.nr5g_snr setRdb('wwan.0.radio_stack.nr5g.snr',v)
    v=o.nr5g_cqi setRdb('wwan.0.radio_stack.nr5g.cqi',v)
    v=o.nr5g_ssbIndex setRdb('wwan.0.radio_stack.nr5g.ssb_index',v)
    v=o.sys_so setRdb('wwan.0.system_network_status.current_system_so',v)
    v=o.scellBand setRdb('wwan.0.system_network_status.lte_ca_scell.list.1.band',v)
    v=o.scellPci setRdb('wwan.0.system_network_status.lte_ca_scell.list.1.pci',v)
    v=o.scellEarfcn setRdb('wwan.0.system_network_status.lte_ca_scell.list.1.freq',v)
    v=o.scellState setRdb('wwan.0.system_network_status.lte_ca_scell.list.1.scell_state',v)
    until(true)
    luardb.unlock()
  end
}
