-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.eth0mac=getRdb('system.product.mac')
    o.handover_mac=getRdb('service.ip_handover.mac_address')
    o.handover_en=getRdb('service.ip_handover.enable')
    
            for line in io.lines('/sys/class/net/eth0/operstate') do
                o.port0sts = line
            end
            if (o.port0sts == 'up') then
                for line in io.lines('/sys/class/net/eth0/speed') do
                    o.port0sts = line .. ' Mbps   /   '
                end
                for line in io.lines('/sys/class/net/eth0/duplex') do
                    if (line == 'full') then
                        o.port0sts = o.port0sts .. 'FDX'
                    else
                        o.port0sts = o.port0sts .. 'HDX'
                    end
                end
            end
            local rdbs = getDefaultRouteLanRdbs()
            o.lan_ip = luardb.get(rdbs.rdbAddrPrefix..'address')
            o.lan_mask = luardb.get(rdbs.rdbAddrPrefix..'netmask')
        
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.eth0mac setRdb('system.product.mac',v)
    v=o.handover_mac setRdb('service.ip_handover.mac_address',v)
    v=o.handover_en setRdb('service.ip_handover.enable',v)
    until(true)
  end
}
