-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.version=getRdb('sw.version')
    o.identityTitle=getRdb('system.product.title')
    o.deviceModel=getRdb('system.product.model')
    o.hw_ver=getRdb('system.product.hwver')
    o.moduleFirmwareVersion=getRdb('wwan.0.firmware_version')
    o.moduleModel=getRdb('wwan.0.module_model_name')
    o.serialNumber=getRdb('system.product.sn')
    o.moduleHardwareVersion=getRdb('wwan.0.hardware_version')
    o.imei=getRdb('wwan.0.imei')
    for line in io.lines('/proc/uptime') do o.uptime = line break end
    o.manuDate = executeCommand('environment -r MFG_DATE')
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.version setRdb('sw.version',v)
    v=o.identityTitle setRdb('system.product.title',v)
    v=o.deviceModel setRdb('system.product.model',v)
    v=o.hw_ver setRdb('system.product.hwver',v)
    v=o.moduleFirmwareVersion setRdb('wwan.0.firmware_version',v)
    v=o.moduleModel setRdb('wwan.0.module_model_name',v)
    v=o.serialNumber setRdb('system.product.sn',v)
    v=o.moduleHardwareVersion setRdb('wwan.0.hardware_version',v)
    v=o.imei setRdb('wwan.0.imei',v)
    until(true)
  end
}
