-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/gps_configuration.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.number_of_satellites=getRdb('sensors.gps.0.standalone.number_of_satellites')
    o.satellitedata=getRdb('sensors.gps.0.standalone.satellitedata')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.number_of_satellites setRdb('sensors.gps.0.standalone.number_of_satellites',v)
    v=o.satellitedata setRdb('sensors.gps.0.standalone.satellitedata',v)
    until(true)
    luardb.unlock()
  end
}
