-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/service_assurance.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.dnsToLookup=getRdb('service.service_assurance.conf.dns_to_look_up')
    o.pingDest=getRdb('service.service_assurance.conf.ping_dest')
    o.curlDest=getRdb('service.service_assurance.conf.curl_dest')
    o.curlMethod=getRdb('service.service_assurance.conf.curl_method')
    
            local profiles = getRdbArray(authenticated, 'link.profile', 1, 6, false, {'apn','module_profile_idx', 'defaultroute'}, false)
            local policies = getRdbArray(authenticated, 'link.policy', 1, 6, false, {'enable','module_profile_idx'}, false)
            local defaultProfileId
            for idx, profile in pairs(profiles) do
                local m_policy = policies[idx]
                if type(m_policy) == "table" and m_policy.module_profile_idx == profile.module_profile_idx then
                    profile.enable = m_policy.enable
                else
                    for _, policy in pairs(policies) do
                        if policy.module_profile_idx == profile.module_profile_idx then
                            profile.enable = policy.enable
                        end
                    end
                end
                if profile.enable == "1" and profile.defaultroute == "1" then
                    defaultProfileId = profile.__id
                end
            end
            o.profiles = profiles
            local selectedProfileIndexes = getRdb("service.service_assurance.conf.selected_profile_indexes")
            if selectedProfileIndexes == "" and defaultProfileId then
                selectedProfileIndexes = tostring(defaultProfileId)
            end
            o.selectedProfileIndexes = selectedProfileIndexes:explode(" ")
        
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.dnsToLookup if #v > 0 then if (#v<=128)==false then return false,'oops! '..'dnsToLookup' end end
    v=o.pingDest if #v > 0 then if (#v<=128)==false then return false,'oops! '..'pingDest' end end
    v=o.curlDest if #v > 0 then if (#v<=128)==false then return false,'oops! '..'curlDest' end end
    v=o.curlMethod if isValid.Enum(v,{'GET','PUT'})==false then return false,'oops! '..'curlMethod' end
    
            if #o.dnsToLookup > 0 then
                if not isValid.Hostname(o.dnsToLookup) then
                    return false, "Invalid dnsToLookup"
                end
            end
            if #o.pingDest > 0 then
                if not isValid.Hostname(o.pingDest) and not isValid.Ipv6Address(o.pingDest) then
                    return false, "Invalid pingDest"
                end
            end
            if #o.curlDest > 0 then
                if not isValid.URL(o.curlDest) then
                    return false, "Invalid curlDest"
                end
            end
            if o.selectedProfileIndexes ~= "" then
                local profile_indexes = o.selectedProfileIndexes:explode(",")
                for _, idx in pairs(profile_indexes) do
                    local idx_num = tonumber(idx) or 0
                    if idx_num < 1 or idx_num > 6 then
                        return false, "Invalid profile indexes"
                    end
                end
            end
        
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.dnsToLookup setRdb('service.service_assurance.conf.dns_to_look_up',v)
    v=o.pingDest setRdb('service.service_assurance.conf.ping_dest',v)
    v=o.curlDest setRdb('service.service_assurance.conf.curl_dest',v)
    v=o.curlMethod setRdb('service.service_assurance.conf.curl_method',v)
    until(true)
    
            setRdb("service.service_assurance.conf.selected_profile_indexes", o.selectedProfileIndexes:gsub(",", " "))
            setRdb("service.service_assurance.trigger", "1", true)
        
    luardb.unlock()
  end
}
