-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    
                o = {}
                local NumProfiles = luardb.get("wwan.0.max_sub_if") or 6
                o.NumProfiles = NumProfiles
                for pf=1,NumProfiles do
                    local info = {}
                    info.__id = pf
                    info.name = luardb.get("link.profile."..pf..".name") or ""
                    info.status_ipv4 = luardb.get("link.policy."..pf..".status_ipv4") or ""
                    info.status_ipv6 = luardb.get("link.policy."..pf..".status_ipv6") or ""
                    info.mtu_ipv4 = luardb.get("link.policy."..pf..".mtu_ipv4") or ""
                    info.mtu_ipv6 = luardb.get("link.policy."..pf..".mtu_ipv6") or ""
                    info.iplocal = luardb.get("link.policy."..pf..".iplocal") or ""
                    info.dns1 = luardb.get("link.policy."..pf..".dns1") or ""
                    info.dns2 = luardb.get("link.policy."..pf..".dns2") or ""
                    info.ipv6_ipaddr = luardb.get("link.policy."..pf..".ipv6_ipaddr") or ""
                    info.ipv6_dns1 = luardb.get("link.policy."..pf..".ipv6_dns1") or ""
                    info.ipv6_dns2 = luardb.get("link.policy."..pf..".ipv6_dns2") or ""
                    info.apn = luardb.get("link.profile."..pf..".apn") or ""
                    info.enable = luardb.get("link.policy."..pf..".enable") or "0"
                    info.uptime = luardb.get("link.policy."..pf..".sysuptime_at_ifdev_up") or ""
                    info.max_rx_kbps = luardb.get("link.policy."..pf..".stats_max_rx_kbps") or ""
                    info.max_tx_kbps = luardb.get("link.policy."..pf..".stats_max_tx_kbps") or ""
                    info.rx_kbps = luardb.get("link.policy."..pf..".stats_rx_kbps") or ""
                    info.tx_kbps = luardb.get("link.policy."..pf..".stats_tx_kbps") or ""
                    table.insert(o, info)
                end
                for line in io.lines('/proc/uptime') do o.uptime = line break end
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
