-- auto generated by luaScriptGen.js.
function isValidRouteName(val)
 if val and #val >= 1 and #val <= 64 and val:match("[!()*/0-9;?A-Z_a-z-]+") then
  return true
 end
 return false
end
objHandler = {
  pageURL='/routing.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    =getRdbArray(authenticated,'service.router.static.route',0,99,true,{''})
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.name if (#v<=64)==false or isValidRouteName(v)==false then return false,'oops! '..'name' end
    v=o.destIp if isValid.IpAddress(v)==false then return false,'oops! '..'destIp' end
    v=o.destMask if isValid.IpMask(v)==false then return false,'oops! '..'destMask' end
    v=o.gwyIp if isValid.IpAddress(v)==false then return false,'oops! '..'gwyIp' end
    v=o.netIf if isValid.Enum(v,{'auto','wwan','bridge0'})==false then return false,'oops! '..'netIf' end
    v=o.metric if isValid.BoundedInteger(v,0,32766)==false then return false,'oops! '..'metric' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local objs = o.objs
    for _, r in ipairs(objs) do
      r.rawdata=r.name..','..r.destIp..','..r.destMask..','..r.gwyIp..','..r.metric..','..r.netIf
    end
    local termObj = {} termObj.__id=#o.objs  termObj.rawdata = '' o.objs[#o.objs+1]=termObj
    local rc = setRdbArray(authenticated,'service.router.static.route',{''},o)
    luardb.set('service.router.static.route.trigger','1')
    return rc
  end
}
