-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.status=getRdb('sensors.gps.0.common.status')
    o.latitude=getRdb('sensors.gps.0.common.latitude_degrees')
    o.longitude=getRdb('sensors.gps.0.common.longitude_degrees')
    o.altitude=getRdb('sensors.gps.0.common.altitude')
    o.height_of_geoid=getRdb('sensors.gps.0.common.height_of_geoid')
    o.pdop=getRdb('sensors.gps.0.common.pdop')
    o.horizontal_uncertainty=getRdb('sensors.gps.0.common.horizontal_uncertainty')
    o.vertical_uncertainty=getRdb('sensors.gps.0.common.vertical_uncertainty')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.status setRdb('sensors.gps.0.common.status',v)
    v=o.latitude setRdb('sensors.gps.0.common.latitude_degrees',v)
    v=o.longitude setRdb('sensors.gps.0.common.longitude_degrees',v)
    v=o.altitude setRdb('sensors.gps.0.common.altitude',v)
    v=o.height_of_geoid setRdb('sensors.gps.0.common.height_of_geoid',v)
    v=o.pdop setRdb('sensors.gps.0.common.pdop',v)
    v=o.horizontal_uncertainty setRdb('sensors.gps.0.common.horizontal_uncertainty',v)
    v=o.vertical_uncertainty setRdb('sensors.gps.0.common.vertical_uncertainty',v)
    until(true)
    luardb.unlock()
  end
}
