-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.networkRegistration=getRdb('wwan.0.system_network_status.reg_stat')
    o.simStatus=getRdb('wwan.0.sim.status.status')
    o.pukRetries=getRdb('wwan.0.sim.status.retries_puk_remaining')
    o.provider=getRdb('wwan.0.system_network_status.network')
    o.connType=getRdb('wwan.0.system_network_status.service_type')
    o.csq=getRdb('wwan.0.radio.information.signal_strength')
    o.coverage=getRdb('wwan.0.system_network_status.system_mode')
    o.roamingStat=getRdb('wwan.0.system_network_status.roaming')
    o.simICCID=getRdb('wwan.0.system_network_status.simICCID')
    o.manualroamResetting=getRdb('manualroam.resetting')
    o.IMSI=getRdb('wwan.0.imsi.msin')
    o.autopin=getRdb('wwan.0.sim.autopin')
    o.operationMode=getRdb('wwan.0.PLMN_selectionMode')
    o.currBand=getRdb('wwan.0.system_network_status.current_band')
    o.nr5gStatus=getRdb('wwan.0.radio_stack.nr5g.up')
    o.endcAvail=getRdb('wwan.0.system_network_status.endc_avail')
    o.dcnrRestricted=getRdb('wwan.0.system_network_status.dcnr_restricted')
    o.signalBar=getRdb('system.signal_bar_threshold')
    o.serviceOption=getRdb('wwan.0.system_network_status.current_system_so')
    require('stringutil')
    o.coverage_format = 'string'
    local rdbBands = luardb.get('wwan.0.currentband.current_selband') or ''
    local rawBandList = rdbBands:explode(';')
    local cdmaBandList, gsmBandList, wcdmaBandList, lteBandList = {}, {}, {}, {}
    local nr5gBandList, nr5gNsaBandList, nr5gSaBandList = {}, {}, {}
    for _, v in ipairs(rawBandList) do
      if v:find('all') == nil then
        if v:find('WCDMA') then
          table.insert(wcdmaBandList, v)
        elseif v:find('CDMA') then
          table.insert(cdmaBandList, v)
        elseif v:find('GSM') then
          table.insert(gsmBandList, v)
        elseif v:find('LTE Band') then
          table.insert(lteBandList, v:match('LTE Band (%d+).*'))
        elseif v:find('NR5G BAND') then
          table.insert(nr5gBandList, v:match('NR5G Band (%d+).*'))
        elseif v:find('NR5G NSA BAND') then
          table.insert(nr5gNsaBandList, v:match('NR5G NSA BAND (%d+).*'))
        elseif v:find('NR5G SA BAND') then
          table.insert(nr5gSaBandList, v:match('NR5G SA BAND (%d+).*'))
        end
      end
    end
    o.cdmaBandList = cdmaBandList
    o.gsmBandList = gsmBandList
    o.wcdmaBandList = wcdmaBandList
    o.lteBandList = lteBandList
    o.nr5gBandList = nr5gBandList
    o.nr5gNsaBandList = nr5gNsaBandList
    o.nr5gSaBandList = nr5gSaBandList
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.networkRegistration setRdb('wwan.0.system_network_status.reg_stat',v)
    v=o.simStatus setRdb('wwan.0.sim.status.status',v)
    v=o.pukRetries setRdb('wwan.0.sim.status.retries_puk_remaining',v)
    v=o.provider setRdb('wwan.0.system_network_status.network',v)
    v=o.connType setRdb('wwan.0.system_network_status.service_type',v)
    v=o.csq setRdb('wwan.0.radio.information.signal_strength',v)
    v=o.coverage setRdb('wwan.0.system_network_status.system_mode',v)
    v=o.roamingStat setRdb('wwan.0.system_network_status.roaming',v)
    v=o.simICCID setRdb('wwan.0.system_network_status.simICCID',v)
    v=o.manualroamResetting setRdb('manualroam.resetting',v)
    v=o.IMSI setRdb('wwan.0.imsi.msin',v)
    v=o.autopin setRdb('wwan.0.sim.autopin',v)
    v=o.operationMode setRdb('wwan.0.PLMN_selectionMode',v)
    v=o.currBand setRdb('wwan.0.system_network_status.current_band',v)
    v=o.nr5gStatus setRdb('wwan.0.radio_stack.nr5g.up',v)
    v=o.endcAvail setRdb('wwan.0.system_network_status.endc_avail',v)
    v=o.dcnrRestricted setRdb('wwan.0.system_network_status.dcnr_restricted',v)
    v=o.signalBar setRdb('system.signal_bar_threshold',v)
    v=o.serviceOption setRdb('wwan.0.system_network_status.current_system_so',v)
    until(true)
  end
}
