-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/service_assurance.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.status=getRdb('service.service_assurance.status')
    o.progressStage=getRdb('service.service_assurance.progress_stage')
    o.error=getRdb('service.service_assurance.error')
    o.selectedProfileIndexes=getRdb('service.service_assurance.conf.selected_profile_indexes')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    until(true)
    luardb.unlock()
  end
}
