-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/status.html',
  authenticatedOnly=false,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o = {}
    local addr = nil
    local retTbl = executeCommand('hciconfig hci0')
    for _, v in ipairs(retTbl) do
      addr = v:match('^%s+BD Address: ([A-Fa-f0-9:]+).*')
      if addr then break end
    end
    o.bt0mac = addr
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
  end
}
