-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/dhcp.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    =getRdbArray(authenticated,'service.dhcp.static',0,99,true,{'','pc'})
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.sname if (#v<=64)==false or isValidName(v)==false then return false,'oops! '..'sname' end
    v=o.smac if (#v<=17)==false then return false,'oops! '..'smac' end
    v=o.sip if isValid.IpAddress(v)==false then return false,'oops! '..'sip' end
    v=o.senable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'senable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local indices = collect_indices(o.objs)
    luardb.set('service.dhcp.static._index', indices)
    local objs = o.objs
    for _, r in ipairs(objs) do
      r.rawdata=''..','..r.smac..','..r.sip..','..r.senable
      r.pc=r.sname
    end
    local termObj = {} termObj.__id=#o.objs  termObj.rawdata = '' termObj.pc = '' o.objs[#o.objs+1]=termObj
    local rc = setRdbArray(authenticated,'service.dhcp.static',{'','pc'},o)
    luardb.set('service.dhcp.static.trigger','1')
    return rc
  end
}
