-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/TR069.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.TR069CfgEnable=getRdb('service.tr069.enable')
    o.acsURL=getRdb('tr069.server.url')
    o.acsUsername=getRdb('tr069.server.username')
    o.acsPassword=encode(getRdb('tr069.server.password'))
    o.connectionRequestUsername=getRdb('tr069.request.username')
    o.connectionRequestPassword=encode(getRdb('tr069.request.password'))
    o.connectionRequestPort=getRdb('tr069.request.port')
    o.managementWwanProfileNo=getRdb('tr069.management_apn.lp_idx')
    o.managementApnTrigger=getRdb('tr069.management_apn.trigger')
    o.periodicEnable=getRdb('tr069.server.periodic.enable')
    o.informPeriod=getRdb('tr069.server.periodic.interval')
    o.enableRandomInform=getRdb('tr069.server.random_inform.enable')
    o.randomInformWindow=getRdb('tr069.server.random_inform.window')
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.TR069CfgEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'TR069CfgEnable' end if toBool(v) == false then return true end
    v=o.acsURL if isValid.URL(v)==false then return false,'oops! '..'acsURL' end
    v=o.acsUsername if #v > 0 then if isValid.Hostname(v)==false then return false,'oops! '..'acsUsername' end end
    v=o.connectionRequestUsername if #v > 0 then if isValid.Hostname(v)==false then return false,'oops! '..'connectionRequestUsername' end end
    v=o.connectionRequestPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'connectionRequestPort' end
    v=o.periodicEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'periodicEnable' end
    v=o.informPeriod if isValid.BoundedInteger(v,30,2592000)==false then return false,'oops! '..'informPeriod' end
    v=o.enableRandomInform if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enableRandomInform' end
    v=o.randomInformWindow if isValid.BoundedInteger(v,0,3600)==false then return false,'oops! '..'randomInformWindow' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.TR069CfgEnable setRdb('service.tr069.enable',v) if toBool(v) == false then break end
    v=o.acsURL setRdb('tr069.server.url',v)
    v=o.acsUsername setRdb('tr069.server.username',v)
    v=o.acsPassword v=decode(v) setRdb('tr069.server.password',v)
    v=o.connectionRequestUsername setRdb('tr069.request.username',v)
    v=o.connectionRequestPassword v=decode(v) setRdb('tr069.request.password',v)
    v=o.connectionRequestPort setRdb('tr069.request.port',v)
    v=o.managementWwanProfileNo setRdb('tr069.management_apn.lp_idx',v)
    v=o.managementApnTrigger setRdb('tr069.management_apn.trigger',v,true)
    v=o.periodicEnable setRdb('tr069.server.periodic.enable',v)
    v=o.informPeriod setRdb('tr069.server.periodic.interval',v)
    v=o.enableRandomInform setRdb('tr069.server.random_inform.enable',v)
    v=o.randomInformWindow setRdb('tr069.server.random_inform.window',v)
    until(true)
    
        local profileIdx = o.managementWwanProfileNo
        if profileIdx == '' then
          profileIdx = getDefaultRouteProfileIdx()
        end
        setRdb('link.profile.'..profileIdx..'.admin_access_allowed', '1')
      
  end
}
