-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/TR069.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.startat=getRdb('tr069.informStartAt')
    o.endat=getRdb('tr069.informEndAt')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.startat setRdb('tr069.informStartAt',v)
    v=o.endat setRdb('tr069.informEndAt',v)
    until(true)
    luardb.unlock()
  end
}
