-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/TR069.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.manufacturerOui=getRdb('systeminfo.oui')
    o.serialNumber=getRdb('systeminfo.serialnumber')
    
        o.modelname = luardb.get("tr069.system.product.model") or ""
        if o.modelname == "" then
          o.modelname = luardb.get("system.product.model") or ""
        end
        o.description = luardb.get("tr069.system.product.title") or ""
        if o.description == "" then
          o.description = luardb.get("system.product.title") or ""
        end
        o.productClass = luardb.get("tr069.system.product.class") or ""
        if o.productClass == "" then
          o.productClass = luardb.get("system.product.class") or ""
        end
      
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.manufacturerOui setRdb('systeminfo.oui',v)
    v=o.serialNumber setRdb('systeminfo.serialnumber',v)
    until(true)
  end
}
