-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/NTP.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.tzSel=getRdb('system.config.tz')
    zoneinfo = {}
    o = {}
    local index_file = '/usr/zoneinfo.ref'
    for line in io.lines(index_file) do
      local zone = line:explode(';')
      local info = {}
      info.FL = zone[1]
      info.TZ = zone[2]
      info.DST = zone[3]
      info.NAME = zone[4]
      table.insert(zoneinfo, info)
    end
    o.zoneInfo = zoneinfo
    o.tzSel = luardb.get('system.config.tz')
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    v=o.tzSel setRdb('system.config.tz',v)
    until(true)
  end
}
