-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/web_server_setting.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.certUploader=getFiles('/usrdata/cache/web_https_cert/upload.zip')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    until(true)
    luardb.unlock()
  end
}
