-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/logsettings.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.buffersizekb=getRdb('service.syslog.option.buffersizekb')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.buffersizekb if isValid.BoundedInteger(v,100,512)==false then return false,'oops! '..'buffersizekb' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.buffersizekb setRdb('service.syslog.option.buffersizekb',v)
    until(true)
    luardb.unlock()
  end
}
