-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/vlan.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.vlanEnable=getRdb('vlan.enable')
    o.enableTrigger=getRdb('vlan.trigger')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.vlanEnable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'vlanEnable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.vlanEnable setRdb('vlan.enable',v)
    v=o.enableTrigger setRdb('vlan.trigger',v)
    until(true)
    luardb.unlock()
  end
}
