-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/vlan.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true},
      writeGroups={root=true,admin=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    
        local rawobj=getRdbArray(authenticated,'vlan',0,49,false,{'rule_name','enable','id','address','netmask','dhcp.range','dhcp.lease','dhcp.enable','admin_access_allowed','interface','name','mac_address'})
        -- vlan.num is the last index of vlan rules
        local lastIndex = tonumber(luardb.get('vlan.num'))
        for idx, obj in ipairs(rawobj) do
          if idx > lastIndex then break end
          if rawobj[idx]['id'] ~= '' then
            if rawobj[idx]['address'] and rawobj[idx]['address'] ~= '' then
              rawobj[idx]['dhcp_lease'] = rawobj[idx]['dhcp.lease']
              rawobj[idx]['dhcp_range'] = rawobj[idx]['dhcp.range']
              rawobj[idx]['dhcp_enable'] = rawobj[idx]['dhcp.enable']
            else
              rawobj[idx]['dhcp_lease'] = ''
              rawobj[idx]['dhcp_range'] = ''
              rawobj[idx]['dhcp_enable'] = ''
            end
            table.insert(o, rawobj[idx])
          end
        end
    
    return o
  end,
  validate=function(o, requestHandler)
    local v
    local v_ip
    local v_mask
    v=o.rule_name if (#v<=32)==false or isValidName(v)==false then return false,'oops! '..'rule_name' end
    v=o.id if isValid.VlanIdRange(v)==false then return false,'oops! '..'id' end
    v_ip=o.address if isValid.VlanIpAddress(v_ip)==false then return false,'oops! '..'address' end
    v_mask=o.netmask if isValid.IpMask(v_mask)==false then return false,'oops! '..'netmask' end
    v=o.dhcp_enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'dhcp_enable' end if toBool(v) == false then return true end
    v=o.startRange if isValid.VlanRange(v,v_ip,v_mask)==false then return false,'oops! '..'startRange' end
    v=o.endRange if isValid.VlanRange(v,v_ip,v_mask)==false then return false,'oops! '..'endRange' end
    v=o.dhcp_lease if isValid.BoundedInteger(v,120,99999)==false or (#v<=5)==false then return false,'oops! '..'dhcp_lease' end
    v=o.admin_access_allowed if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'admin_access_allowed' end
    v=o.enable if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'enable' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
    
      local lastIndex = -1
      for idx, obj in ipairs(o.objs) do
        o.objs[idx]['dhcp.lease'] = o.objs[idx]['dhcp_lease']
        o.objs[idx]['dhcp.range'] = o.objs[idx]['dhcp_range']
        o.objs[idx]['dhcp.enable'] = o.objs[idx]['dhcp_enable']
        local ifname = o.objs[idx].interface or ''
        local vlan_id = o.objs[idx].id or ''
        if ifname ~='' and vlan_id ~= '' then
          o.objs[idx].name = ifname .. '.' .. vlan_id
        end
        if not o.objs[idx].__deleted and o.objs[idx].__id > lastIndex then
          lastIndex = o.objs[idx].__id
        end
      end
      local rc = setRdbArray(authenticated,'vlan',{'rule_name','enable','id','address','netmask','dhcp.range','dhcp.lease','dhcp.enable','admin_access_allowed','interface','name','mac_address'},o)
      luardb.set('vlan.num',lastIndex + 1)
      luardb.set('vlan.trigger','1')
      return rc
    
  end
}
