-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/webui_credentials.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    o.username = requestHandler.session.user
    return o
  end,
  validate=function(o, requestHandler)
    local v
    local cp = decode(o.currentPassword) if #cp <= 0 or #cp > 64 then return false, 'oops! current password' end
    if o.confirmNewPassword ~= o.newPassword then return false, 'oops! confirm password' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    repeat
    until(true)
    local cmd = string.format('/usr/bin/changing_webui_password.sh "'..requestHandler.session.user..'" "%s" "%s" >/dev/null 2>&1; echo $?', o.currentPassword, o.newPassword)
    local ret = executeCommand(cmd)
    local retNum = tonumber(ret[1])
    if retNum == 200 then return retNum,'The current password is incorrect.' else return retNum end
  end
}
