-- auto generated by luaScriptGen.js.
objHandler = {
  pageURL='/web_server_setting.html',
  authenticatedOnly=true,

      readGroups={root=true,admin=true,user=true},
      writeGroups={root=true,admin=true,user=true},
      get=function(authenticated, requestHandler)
    local o
    ={}
    luardb.lock()
    o.httpsEn=getRdb('service.webserver.https_enabled')
    o.httpsPort=getRdb('service.webserver.https_port')
    o.httpPort=getRdb('service.webserver.http_port')
    o.trigger=getRdb('service.webserver.trigger')
    luardb.unlock()
    return o
  end,
  validate=function(o, requestHandler)
    local v
    v=o.httpsEn if isValid.BoolOrEmpty(v)==false then return false,'oops! '..'httpsEn' end
    v=o.httpsPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'httpsPort' end
    v=o.httpPort if isValid.BoundedInteger(v,1,65535)==false then return false,'oops! '..'httpPort' end
    return true
  end,
  set=function(authenticated, o, requestHandler)
    local v
    luardb.lock()
    repeat
    v=o.httpsEn setRdb('service.webserver.https_enabled',v)
    v=o.httpsPort setRdb('service.webserver.https_port',v)
    v=o.httpPort setRdb('service.webserver.http_port',v)
    v=o.trigger setRdb('service.webserver.trigger',v)
    until(true)
    luardb.unlock()
  end
}
